### ISSUE TITLE
Set up basic framework for client and server applications

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#1]
We need to set up the basic framework. I propose that we use a React front end built using [create-react-app](https://github.com/facebookincubator/create-react-app) and an express back end. Based on [this blog post](https://www.fullstackreact.com/articles/using-create-react-app-with-a-server/), I've created the resulting combined framework in the [_init-framework_](https://github.com/CodeForNC/reentry-resources-hub/tree/init-framework) branch of this repository. I have added in Bootstrap, following the create-react-app instructions for that.

Right now the server is not tied in any way to the front end, other than having the dev-server set up to proxy to it.

Full documentation on create-react-app is still included in the README in the client directory.

If there are no objections to this framework, I'll merge into the master branch next week.

**Comment by ejaxon** [comment]
@marshallj Please review and let me know if you think this approach is ok.

**Comment by marshallj** [comment]
@ejaxon I like the approach. My vote is to move forward with it.

**Comment by ejaxon** [comment]
Cool - I've merged in. Closing this issue.
