### ISSUE TITLE
Review Draft Pull Request Template

### ISSUE THREAD

**Issue by marshallj** [CodeForNC/reentry-resources-hub#11]
## This is a (check all that apply):
* [ ] bug
* [ x ] enhancement
* [ x ] feature-discussion

### Draft Pull Request template at the link below for review and feedback. 

https://github.com/CodeForNC/reentry-resources-hub/blob/content-arch/.github/PULL_REQUEST_TEMPLATE.md

Questions that need consensus for final version of template:

- Will we accept pull requests without discussing in an issue first? Currently the template indicates that pull requests must be submitted after discussing in an issue first.
- How will we test code in pull requests, manually, or with automated tests?

## Current Behavior

N/A

## Possible Solution

N/A
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Define how Pull Requests are managed for this project.

## Your Environment

* Version used: N/A
* Environment name and version (e.g. Chrome 39, node.js 5.4): N/A
* Operating System and version (desktop or mobile): N/A
* Link to your project: N/A

**Comment by ejaxon** [comment]
Basically looks good. Re: questions:

 - I assume that a discussion can be had on the pull request itself, so I don't think we need to require that someone create an issue before doing a pull request. We should strongly encourage filing an issue for discussion BEFORE starting work though to reduce likelihood the pull request is rejected.

 - I think we should have a set of standard tests (and a pull request would probably add regression or new unit tests). However, I am terrible about testing, so somebody else needs to take the lead role on that. I promise I will fall in line if given guidance :).
