### ISSUE TITLE
Write introductions for all topics (information valid for all counties)

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#16]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion
 
# Enhancement
## Description

We need common introductions written for each of the pages/topic areas below. These introductions should be valid for ALL counties in the state, i.e., they should not include information specific to any particular county.

* [ ] Home
* [x] Housing
* [ ] Jobs
* [ ] Public Benefits
* [ ] Health Care
* [ ] Education
* [ ] Legal
* [ ] Support Programs
* [ ] Other Resources

If you take on a topic, let @ejaxon or @marshallj know in the comments below and we will mark it as in progress.

## Implementation

You should take the content from the corresponding pages of the original [Buncombe County site](http://www.buncombereentryhub.org/) since that information has been reasonably well vetted by subject-area experts.

The content will need to be in HTML and added to this repository, but if you are not comfortable doing that, feel free to compose in a text editor, Word, or Google Docs and then work with a developer to translate into HTML and merge into the code. 

The content for a given topic X goes in the corresponding ````content/pages/X/description.txt```` file.

**Comment by sparklebunny** [comment]
@ejaxon @marshallj I will start working on Housing content and can move down the line once it's done.

**Comment by ejaxon** [comment]
Excellent! Does it make sense to create an issue for each as you do it? I hesitated to create them all up front, but it might be a good way to track.

**Comment by marshallj** [comment]
@sparklebunny awesome! Thanks for jumping in. @ejaxon if you think we need discussion on each topic, it would probably be best to track separately. Although, if we are just checking them off as they are completed with minimal comments needed, I vote to continue in this issue.

**Comment by ejaxon** [comment]
I think it's pretty likely that we'll have discussion about the individual bits of content, but it's ok by me to just have initial discussion in the pull request and create the new issue if anyone needs to ask for a revision.

**Comment by sparklebunny** [comment]
Have some copy to commit, just working on setting up my environment. Was on vacation last week :) Plan to get it committed tomorrow.

**Comment by sparklebunny** [comment]
@ejaxon @marshallj I can start working on the Jobs intro if it's still open. Let me know if the Housing copy is what you're looking for or how I can change it. Thanks!

**Comment by ejaxon** [comment]
Hey @sparklebunny, I'll take a look early this coming week. I've been on vacation (and today is a long drive back home). Re: Jobs intro, go for it!

**Comment by ejaxon** [comment]
Still digging out after vacation @sparklebunny, but will review whatever you've got this weekend or before.

**Comment by sparklebunny** [comment]
@ejaxon No worries - having a busy week myself. Should have the job copy up by this weekend. Thanks!

**Comment by sparklebunny** [comment]
@ejaxon I can start on Public Benefits general copy if no one else has claimed it. Again, let me know if you'd like any changes to the Jobs or Housing copy. Thanks!

**Comment by ejaxon** [comment]
Go for it. At this point you're the only one working on this piece, so feel free to move ahead.

**Comment by ejaxon** [comment]
Closing this as part of a reorganization of the work.
