### ISSUE TITLE
Write a server topic page renderer for the public site (Node Express)

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#17]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

__Note:__ Implementation of this issue depends on and should follow that of [issue 18](https://github.com/CodeForNC/reentry-resources-hub/issues/18).

# Enhancement
## Description

The standard topic route for the public reentry site is ````/{jurisdiction}/{topic}```` 
where ````jurisdiction```` is a county name and ````topic```` is one of home, housing, jobs, benefits, health, education, legal, support, or other. 

The route is partially implemented in [server.js](https://github.com/CodeForNC/reentry-resources-hub/blob/master/server.js). The route calls a ````compose```` function that traverses the content directory and pulls together all the information needed to construct a topic page. The structure of the object returned is show at the end of this issue description. At the moment the route simply renders this structure as JSON.

The task here is to implement a renderer that takes this information and renders it in a page that follows the structure defined [here](https://github.com/CodeForNC/reentry-resources-hub/blob/master/documentation/README.md). 

It is preferable to use either a simple templating library or server-side React, rather than simply constructing the page manually.

````json
{
    "config": {
        "common_jurisdiction_name": "North Carolina",
        "common_jurisdiction": "nc",
        "page_name": "Housing",
        "page_tag": "housing",
        "local_jurisdiction_name": "Buncombe",
        "local_jurisdiction": "buncombe"
    },
    "common": {
        "description": "<p>\n  Common Housing: Sample Text\n</p>\n",
        "highlighted": {
            "resources": []
        },
        "local": {
            "resources": [{
                "name": "Home Rental Listings",
                "link": "http://www.icarol.info/Search.aspx?org=82852&Count=5&Search=Home+Rental+Listings&NameOnly=True&pst=Coverage&sort=Proximity&TaxExact=False&Country=United%20States&StateProvince={{common_jurisdiction}}&County={{local_jurisdiction}}&City=-1",
                "region": []
            }]
        }
    },
    "jurisdiction": {
        "description": "<p>\n  Housing: Sample Text\n</p>\n",
        "highlighted": {
            "resources": []
        },
        "local": {
            "resources": []
        }
    }
}
````

**Comment by marshallj** [comment]
@ejaxon - https://github.com/CodeForNC/reentry-resources-hub/blob/master/documentation/content.md is a dead link.

**Comment by ejaxon** [comment]
Sorry - restructured the documentation. Fixed now.

**Comment by ejaxon** [comment]
Closing this as part of a reorganization of the work.
