### ISSUE TITLE
Create base HTML page template (& add templating language)

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#18]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description
Currently the server has a single route which reads the information required to build a topic page but has no HTML rendering. We need to create the base HTML page that we'll use for the site and decide on/implement the templating language we'll use.

## Implementation
I don't have a strong preference for any particular templating language. My feeling is that there's little reason to bother with React - the site is too simple, so the main thing is to pick a well-supported system like [Handlebars.js](https://github.com/wycats/handlebars.js/).

The implementation of this task only requires the base page (with some simple test content) for
the ````'/:jurisdiction/:topic'```` route in ````server.js````.

**Comment by buddyp450** [comment]
@ejaxon would be willing to accept a PR if using react? I haven't used handlebars before but would be willing to check it out.

**Comment by ejaxon** [comment]
Hi, @buddyp450, my thinking was that it's important for consistent SEO for now to do the rendering on the server. If you want to take us down the path of server-rendered React, I'd definitely be up for that. I don't know Handlebars either, but figured it'd be easy to learn and work on the server side.

**Comment by ejaxon** [comment]
Actually, I should say that I'd actually prefer React, but wasn't sure the best way to do server-side rendering and so went with what seemed easier. The admin front-end will be React, so actually better if this is too, as long as we can guarantee good SEO.

**Comment by ejaxon** [comment]
Closing this as part of a reorganization of the work. Will update you on Slack @buddyp450 soon.
