### ISSUE TITLE
Determine deployment approach (including how to push content updates back to Github)

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#19]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description
The content for the reentry site is maintained in plain files contained in the project. There are a couple key advantages to doing it this way, namely, that all content is available directly in the Github repository and that we can begin building the site without waiting for administrative tools to be developed.

Nevertheless, we need to have a very usable administrative front-end for subject-area experts and volunteers to update content on the site. We will be creating a (relatively simple) React-based front-end app to serve this purpose. The app will let users add and change descriptions, highlighted resources, and resource links and save the results back to the site.

Note that, while it is easy to save changes back out to the local filesystem, we also need to push those changes back to the Github repository. There are a couple basic approaches.

__Approach 1:__  Use something like Heroku to deploy the site and automatically push changes back to the repository. In this case it is vital that the changes be automatically pushed since the Heroku filesystem is ephemeral - if the dyno is restarted, changes in the filesystem will be lost.

__Approach 2:__ Deploy the site on a server with persistent state (e.g., on AWS or DigitalOcean). In this case, we don't need to automatically update Github immediately since the changes won't be lost on a server reboot. I would propose creating a branch for the server and periodically push changes back to Github. After review, the branch can be merged back into the master branch.

My feeling is that approach 2 is better - I think it is easier to keep control over content changes, and also allows us to maintain, e.g., authorization files on the server that should not live in the repo. However, I would love to get others' input on these (and any other approaches that you can think of).

**Comment by marshallj** [comment]
@ejaxon I like approach 2 as well. In this scenario, just so I have it clear in my head, would a deploy to production workflow go something like this...

1. Make sure all content changes on the production server are merged into the 'server branch' and then merged with master.   
2. Pull updates for deployment from master to 'server branch'.
3. Push from 'server branch' to server (AWS, etc.)

**Comment by ejaxon** [comment]
@marshallj Just to make sure we're saying the same thing, here's a full cycle from initial deployment from the master repo to merging in changes made via the admin tool on the server. I'll use 2 branches: _master_ and _deployed_, where _deployed_ is the branch on the server.

1. Clone the repo to the server
2. Create/checkout the 'deployed' branch
3. Build & deploy the app
4. Admin users make some content changes via the admin app on the server
5. System admin is notified of changes.
6. System admin commits those changes to the local repo, then pushes the changes to the _deployed_ branch in Github.
7. System admin creates a pull request to merge _deployed_ changes into _master_.
8. Content expert(s) review(s) the changes and approve the request, merging the changes into _master_
9. System admin pulls merged changes back into _deployed_ (on Github and on server).

We'll need to come up with a process for 5-9 (and something that automatically notifies us when changes happen). We don't necessarily need to react instantly when a change happens, but we don't want to have a whole bunch of changes to deal with all at once (since there will need to be back and forth about them in many cases). 

This also makes clear that we need to have a log that tracks who makes what changes. 

Probably much to talk about here.

**Comment by ejaxon** [comment]
Closing this as part of a reorganization of the work. We'll come back to this when we're ready. I think we've got a rough idea of approach from this discussion.
