### ISSUE TITLE
Select and implement an authentication system

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#2]
First step is to select a system. I propose that we select from one of the following:

- [Firebase](https://firebase.google.com/docs/auth/)
- [Passport.js](http://passportjs.org/)
- [Everyauth](https://github.com/bnoguchi/everyauth)

We are using Firebase authentication in SimpliCity at the City of Asheville and it is pretty simple to implement. I don't have experience with the other two.

Note that we only need authentication. I think we will have a very simple authorization system - we just need to be able to reliably identify the user.

**Comment by marshallj** [comment]
@ejaxon if you are familiar with Firebase, I vote to move forward with it.

**Comment by ejaxon** [comment]
Considering this a decision (which is documented in issue 12). Closing this issue.
