### ISSUE TITLE
Add authentication to administration site

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#20]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

__Note:__ This feature depends on #21 and must be implemented after or together with it.

# Enhancement
## Description
We will need to be able to identify individual users so that we assign them the authority to change specific content on the site.

## Implementation
My recommendation is that we use Firebase for the authentication and email as their unique identifier. I'd further recommend that we __not__ allow password authentication so that we don't have to store anything for them.

We should definitely support login using Google, Facebook, and Github credentials. We can also use Twitter if they now provide the email address (they didn't the last time I used them, but that may have changed).

For an example that uses Firebase in a Node/React app, check out the new SimpliCity [client](https://github.com/cityofasheville/simplicity2) and [server](https://github.com/cityofasheville/simplicity-graphql-server)

**Comment by tcaddy** [comment]
I am not a Node developer, but it looks like PassportJS is the library to use for this: http://passportjs.org/

**Comment by ejaxon** [comment]
Sorry for the delay - I'm on vacation and have mostly been offline. 

I'm certainly open to that. The advantage of using something like Firebase is that it not only gives you the authentication functionality, but the screens and workflows as well (login, email confirmation, password recovery, etc.). With an authentication library, you need to build that yourself and it is more work than it seems. My thinking was to do something quick that let's us cheaply support authentication against (at least) FB, Github, Google and maybe Twitter and LinkedIn. We can also swap out later for our own implementation.

Thoughts?

**Comment by ejaxon** [comment]
Closing this as part of a reorganization of the work. We'll come back to this when we're ready to start building the admin interface and can decide the best approach then.
