### ISSUE TITLE
Create a newbie contribution tutorial

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#28]
Many of those at brigade meetings who would like to help are newbie developers who know little or nothing not just about the project, but about using Github, coding, etc. Our contribution guide should be targeted specifically at them, helping them begin to contribute by taking them through every step they need to know, including:

* How to sign up for Github
* How to clone a repository
* How to work with Github locally
* How to install and run the project
* How to create a branch, make changes to files and see the results
* How to check in changes and create a pull request
* Etc.

Although we are creating the tutorial for this project initially, those parts that are independent of the specifics of this project will later be extracted into a general tutorial that can be referred to.

Suggestions for doing this task:

* This is for newbies so get newbies to help. They know better than an experienced person what is easy and what is confusing.
* Break the tutorial into parts and create new issues for individual parts. This creates opportunities for new people to contribute. In the end, the tutorial can just be a set of links to files describing different steps along the way.

**Comment by jdmoore4** [comment]
I'm going through a high-level tutorial for git in my coding program at the moment, so I could try and take a stab at some of this.

**Comment by ejaxon** [comment]
Sincere apologies for the slow response - for some reason all my Github notifications started going to my spam folder.

It would great if you could get something started on this, @jdmoore4!

**Comment by marshallj** [comment]
@jdmoore4 have you done any work on this issue? Want to make sure we include anything you've done before the event Saturday. We may have someone that wants to hack here.

**Comment by marshallj** [comment]
@jdmoore4, removing you due to inactivity. Feel free to express interest in contributing here, and we can reassign. Thanks.

**Comment by vinayaugustine** [comment]
I have experience writing introductory tutorials for git & github and would like to take a stab at this. I have less experience setting up node & yarn, so I can definitely bring a newbie perspective to that!

**Comment by ejaxon** [comment]
Hi, @vinayaugustine, sorry for the slow response! Things have been pretty crazy and this project got a bit neglected. We are getting things started back up, but it will probably be a couple weeks before we're ready to talk about new people contributing. If you are still interested in doing this, ping me by email (eric.jackson@democracyapps.org) and we'll set up a conversation.
