### ISSUE TITLE
Make sure that new React content lints cleanly

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#31]
The new server React content shows a lot of ESLint errors. Cleaning them up is also an opportunity to learn React since it's recommending things like specifying prop types, converting stateless classes to functions, etc.

I have been using VS Code as an editor and it's easy then to install ESLint in the editor itself and it will flag all the problems right there.

**Comment by marshallj** [comment]
Reviewed @BlakeGuilloud PR. All looks good. Closing.
