### ISSUE TITLE
Render a topic page using Buncombe healthcare as an example.

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#33]
We have at least demo content for healthcare at both the common level and for Buncombe County (any route other than http://localhost:3001/buncombe/health will fail).

I've updated the documentation in server.js on the structure returned by compose.js. Basically you have 2 HTML blocks (common and local) plus 2 sets of resources at the common level (truly common resources plus resources that are localized via parameters) plus one set of resources at the local level. All HTML content and URLs should be passed through a function to perform any variable replacements from the configuration. 

You will need to use [```dangerouslySetInnerHTML```](https://facebook.github.io/react/docs/dom-elements.html) to add the HTML blocks.

Resources for now are just name, description, URL and category. Take a look at the current [healthcare page](http://www.buncombereentryhub.org/health-care/) - you'll see that the resource list is grouped by category. I suggest we automatically do the same. We should try to maintain the order of resources given, but with category grouping we may have to reorder slightly if the input doesn't keep things grouped.

**Comment by marshallj** [comment]
Marking this complete.
