### ISSUE TITLE
Move common (national & state) content to relevant description.html files in content/pages/*

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#37]
The content for a local content page will be constructed by merging common content and resources that apply nation-wide or state-wide with content and resources relevant to a specific county. The common and Buncombe county sections for health provide a working example of how we're approaching (although it is still subject to change). See content/pages/health and content/jurisdictions/buncombe/health.

This task is to replicate the common (national and state) content from the [current Buncombe county site](http://www.buncombereentryhub.org/) to /content/pages/*/description.html files.

**Comment by ctstrongonline** [comment]
How can I help with this issue? I wan t to help.

**Comment by ejaxon** [comment]
Sincere apologies for the slow response - for some reason all my Github notifications started going to my spam folder. I've also been buried at work and with Open Data Day. By the end of the weekend I'll have a better handle on where this task is (I believe many were done by @sparklebunny over the last week or two.

**Comment by ejaxon** [comment]
This is done. We are getting things cleaned up and there will soon be more opportunity to help out.

@nicolestrong where are you located? Asheville area or Greensboro area or somewhere else?
