### ISSUE TITLE
Write script to set up Centos server on AWS to host site

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#45]
We will host the site (and the administrative API)  on AWS on a [Centos 7 Linux](https://aws.amazon.com/marketplace/pp/B00O7WM7QW?ref=cns_srchrow) server. We need a simple script that will:

* Install git, Nodejs (version 8, not 6), yarn and Nginx
* Clone the 3 code repos and content repo to /opt
* Run yarn on each of the code repos.

**Comment by giancarlopetrini** [comment]
Do you want the script to clean build each time it's run or just fetch after the initial setup?

**Comment by ejaxon** [comment]
I think a clean build is fine. For the most part, we'll almost never do a git pull on this server since the editing will actually be happening there.

**Comment by giancarlopetrini** [comment]
Great, sounds good. I'll start working on it ASAP.

**Comment by marshallj** [comment]
@giancarlopetrini assigning this to you and placing it in progress. We appreciate the help! Let us know if you need anything.r

**Comment by ejaxon** [comment]
Merged this in. Closing the issue now.
