### ISSUE TITLE
Finalize common content

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#46]
Work with Christiana Tugman to update a final version of the common content both on the Buncombe County site and here.

**Comment by sparklebunny** [comment]
Do you and Christiana need any help with this part? Realized there were one or two general descriptions I hadn't finished yet. Let me know if I can help :)

**Comment by ejaxon** [comment]
Hey, @sparklebunny, definitely yes, though I think we'll need to confer and I want to bring someone in from Code for Greensboro as well. Given that we want to launch Buncombe and bring Guilford on pretty quickly, and have interest from Durham, I think it's important to step back and think through what standards/guidelines we want to establish. Our current pages are a bit haphazard and I don't think it serves us to have every page following a slightly different pattern across topics and locations.

Once I connect with the person in Greensboro, maybe the 3 of us can do a Hangout and talk through  how to approach?

**Comment by sparklebunny** [comment]
Great idea! Keep me posted :)

**Comment by ejaxon** [comment]
This is done - we'll have revisions after release.
