### ISSUE TITLE
Domain mapping strategy & implementation

### ISSUE THREAD

**Issue by marshallj** [CodeForNC/reentry-resources-hub#50]
We ultimately need to route requests to the public deployment of the NC Reentry Resources Hub  
through an Nginx proxy. 

Create an Nginx config file that maps county subdomains to the appropriate page on the website. 

Example: guilford.ncreentryhub.org/jobs maps to ncreentryhub.org/guilford/jobs

**Comment by ejaxon** [comment]
Closing for now as part of a general restart.
