### ISSUE TITLE
Sidebar Leaflet Map with NC Counties

### ISSUE THREAD

**Issue by marshallj** [CodeForNC/reentry-resources-hub#52]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

 

# Enhancement
## Description

Create React component that uses Leaflet to provide a map of NC Counties in the sidebar of the page. The appropriate county on the map will highlight based on what county's page the user is viewing.
 
## Implementation

Create a React component for this.
Use Leaflet.
Use geojson file for the county data - Contact @marshallj if you need help finding the data.
Communicate prior to deviating from these requirements to avoid a declined pull request.

**Comment by marshallj** [comment]
Hi @adennen. Thanks for coming out to the Code for NC Reentry Resources Hub Hackday a couple weeks ago! At the event, you indicated you were interested in working on this issue. We would love to have you submit a pull request for this task, although we understand if life is taking your time in other directions. To help us to move the project towards deployment, please comment here to let us know if you are still working on the issue. If you are still working on it include an estimate of when you will be able submit a pull request. If we do not hear from you by this Friday afternoon, August 4th, we will assign the issue to another volunteer developer. Regardless of your ability to contribute now, we would love have you contribute at a later time, and see you at future events! Take care. 
-Jason

**Comment by adennen** [comment]
Hi Jason, I'm interested in putting some hours in on this over the weekend,
is there a deadline this project needs to be ready by?

Thanks, Aron

**Comment by marshallj** [comment]
Sure Aron. Thanks for the heads up. We'd love to have you work on this. There is no locked in deadline, we would just like to keep track of the issues that volunteers are actively working on. Thanks.

**Comment by marshallj** [comment]
@adennen I'm moving this back to the Todo column due to inactivity. Feel free to indicate future interest in contributing. Thanks.

**Comment by ejaxon** [comment]
Closing for now as part of a general restart.
