### ISSUE TITLE
Per-county image

### ISSUE THREAD

**Issue by marshallj** [CodeForNC/reentry-resources-hub#62]
Implement custom images for the header in each county page. We would like each county that has joined the project to have a custom image. A default image should display for all counties that do not have a custom image. We can start with Guilford County. Also, brainstorm and document required stats for images - Height, width, format, etc.

**Comment by marshallj** [comment]
This could perhaps be an issue in the community project for the July 22 hackday.

**Comment by jmu2nmsu** [comment]
I can do this. :)

**Comment by ejaxon** [comment]
Per my comment on [issue](https://github.com/CodeForNC/reentry-resources-hub/issues/72), we should create a top-level /public directory for favicon, images, etc.

**Comment by marshallj** [comment]
Hi @jmu2nmsu. Thanks for coming out to the Code for NC Reentry Resources Hub Hackday a couple weeks ago! At the event, you indicated you were interested in working on this issue. We would love to have you submit a pull request for this task, although we understand if life is taking your time in other directions. To help us to move the project towards deployment, please comment here to let us know if you are still working on the issue. If you are still working on it include an estimate of when you will be able submit a pull request. If we do not hear from you by this Friday afternoon, August 4th, we will assign the issue to another volunteer developer. Regardless of your ability to contribute now, we would love have you contribute at a later time, and see you at future events! Take care. 
-Jason

**Comment by marshallj** [comment]
Moving back to To-Do status.

**Comment by marshallj** [comment]
@Sadaajit, are you still interested in working on this?

**Comment by Sadaajit** [comment]
@Jason, yes. Have been struggling with recovering from a mean respiratory infection, which left me with no energy. Was just thinking about getting back into it. I need to know what size the picture needs to be. Does Eric know?

Sadaajit

**Comment by ejaxon** [comment]
Hi, @Sadaajit, I think the unfortunate answer is: "It depends". Here's one (of very many) articles I found about sizing images (these are full background images rather than headers, but the considerations are similar): https://www.webmalama.com/the-best-full-screen-background-image-sizes-for-web-design/. 

I think we'll probably need to plan to have 2-3 sizes of each image with CSS that selects based on a media query. In the near-term, though, I'd pick a screen resolution and figure out the best height to fit the site design. Another good way is to find some sites that fit what we're going for and see what they use.

@marshallj: perhaps you have less wishy-washy advice?

**Comment by Sadaajit** [comment]
Thanks, @ejaxon. I’ll take a look at the link. Do you know the size of the image that is being used as the header for the original site? That would help me with the size for the largest image.

**Comment by ejaxon** [comment]
That one is 1280X300

**Comment by Sadaajit** [comment]
Great, thanks @ejaxon. That will help me get the ball rolling.

**Comment by ejaxon** [comment]
Hi, @Sadaajit, are you still working on this one?

**Comment by Sadaajit** [comment]
No, sorry, my schedule has gotten busy and I’m trying to launch my own business right now, so all time is being spent there.

Sadaajit

**Comment by ejaxon** [comment]
Not a problem at all. Just didn't want to yank it out from under you if you still wanted to work on it. I'm closing this for now as part of a general restart of the project.

**Comment by Sadaajit** [comment]
Thanks for checking and letting me know.

Sadaajit
