### ISSUE TITLE
Set up files and scripts to deploy the site on a Centos 7 Linux server

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#63]
To deploy the site, we need to set up an Nginx web server that proxies calls to the Node server.

You can find a guide to how it's done [here](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-centos-7).

In addition, you will find a `deployment` directory in [this repository](https://github.com/cityofasheville/simplicity-graphql-server) that can serve as an example of a working deployment (for the City of Asheville's SimpliCity GraphQL API server).

**Comment by marshallj** [comment]
@ejaxon is the deliverable for this issue a nginx config file with the proper subdomain mapping? Asking to clarify the existing issue [here](https://github.com/CodeForNC/reentry-resources-hub/issues/50) we have for that piece. If this one covers it, I will close the old one.

**Comment by marshallj** [comment]
Doh! Didn't mean to close this! Reopened now.

**Comment by ejaxon** [comment]
Yes, they are related, but I think we could go ahead and deploy the ncreentryhub.org common domain and figure out domain mapping separately. I may not be thinking about this clearly, though.

**Comment by marshallj** [comment]
Great, I'll add the other issue for config for the subdomain routing to the hackday project.

**Comment by ejaxon** [comment]
Closing this since we've taken a different tack.
