### ISSUE TITLE
Fix the production build of reentry hub by adding minification/uglification/best practices

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#64]
Prepare a complete and robust webpack production build for the app including minification, uglification, and image optimization. See the info [here](https://webpack.js.org/guides/production/) to get started. Contact @marshallj with questions.

**Comment by ejaxon** [comment]
@marshallj - Could you please add a better description to this.

**Comment by BlakeGuilloud** [comment]
I think that using the react-scripts package / config that we are using should resolve this issue.

**Comment by marshallj** [comment]
@BlakeGuilloud I haven't had a chance to look. Are changes needed for this now, or did Brendan's React-snapshot PR take care of it?

**Comment by BlakeGuilloud** [comment]
@marshallj running `yarn build` will populate the `build` folder with optimized resources. The build folder is what should be deployed.

**Comment by marshallj** [comment]
@BlakeGuilloud I thought that was the case, Closing this now. Thanks for helping Eric and I clean these issues up.
