### ISSUE TITLE
Improve dev environment by implementing hot reloading

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#66]
We need to implement a proper development webpack configuration including hot reloading for a universal (isomorphic) JavaScript app. There are several ways to do this, but the blog posts [here](https://medium.com/@justinjung04/react-server-side-rendering-and-hot-reloading-ffb87ca81a89) and [here](https://hackernoon.com/isomorphic-universal-boilerplate-react-redux-server-rendering-tutorial-example-webpack-compenent-6e22106ae285) may help get up to speed. Contact @marshallj with questions.

**Comment by ejaxon** [comment]
@marshallj please enhance the description.

**Comment by brendanyounger** [comment]
There's a partial solution to this at https://github.com/brendanyounger/reentry-resources-hub.

I disabled server-side rendering for the time being, but it shouldn't be too hard to add back.  I haven't created a pull request, because it needs some cleanup before merging.

**Comment by marshallj** [comment]
@brendanyounger thanks for working on this. I'll pull what you've done down and take a look.

**Comment by matthannam** [comment]
@marshallj Can we merge Brendan's pull request that fixes hot reload?  It works great for me.  I'm sure everybody is ready to have this working properly for their dev environment.

**Comment by ejaxon** [comment]
Ignore this if it throws a wrench in the works, but one thing to think about is eventually just dropping the back-end part of this and replacing with connection to the GraphQL server we've built for the admin ui. It can easily be done using the existing API endpoints, but easy enough to create a new one that is optimized for the public site. 

If getting the server-side hot-reload is hard, this might be an argument for not worrying about it for now and maybe even accelerating the switch. The big question there is whether we have a long-term problem with search optimization. I don't know enough about where things are headed to say.

Anyone have thoughts on this?

**Comment by marshallj** [comment]
@ejaxon, I think your suggestion may be the right decision for now. I spent several hours yesterday trying to configure the server side hot reloading, and could not get the bundle to compile without errors. Brendan suggested a solution, but I'm not familiar with the approach and it doesn't appear to support server side hot loading. If we pull out the server side rendering, we would be removing a substantial amount of this complexity. Let me think on this a little more today, and report back.

**Comment by BlakeGuilloud** [comment]
Has any sort of decision been made on this?

**Comment by ejaxon** [comment]
I think @marshallj has more context on this one.

**Comment by marshallj** [comment]
@ejaxon, @BlakeGuilloud Sorry for the delay. Hot reloading should be working on the client side. Closing.
