### ISSUE TITLE
Rewrite the functions in server/compose.js to use async/await

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#68]
The `compose` and `mainCompose` functions that pull together content for a page are written using callbacks, which make them hard to read and follow, especially for less experienced Javascript developers. 

Beginning in Node 7, however, there is support for a much simpler paradigm for handling asynchronous function calls. The async/await features allow asynchronous code to be written in a way that looks like they are in fact synchronous calls. 

We are standardizing on Node 8 and and to simplify these functions to use the new paradigm. You can find a recent tutorial [here](https://blog.risingstack.com/mastering-async-await-in-nodejs/) and others can be found easily.

**Comment by marshallj** [comment]
Hi @kumarchjava. Thanks for coming out to the Code for NC Reentry Resources Hub Hackday a couple weeks ago! At the event, you indicated you were interested in working on this issue. We would love to have you submit a pull request for this task, although we understand if life is taking your time in other directions. To help us to move the project towards deployment, please comment here to let us know if you are still working on the issue. If you are still working on it include an estimate of when you will be able submit a pull request. If we do not hear from you by this Friday afternoon, August 4th, we will assign the issue to another volunteer developer. Regardless of your ability to contribute now, we would love have you contribute at a later time, and see you at future events! Take care. 
-Jason

**Comment by marshallj** [comment]
Moving back to To-Do status.

**Comment by BlakeGuilloud** [comment]
I'm happy to knock this out over the week. Just confirming our servers are going to be running Node 8? Otherwise I can write some scripts to compile.

**Comment by BlakeGuilloud** [comment]
Scratch that - just read the description again. Looks like we're standard on 7

**Comment by ejaxon** [comment]
Cool - go for it!

**Comment by ghost** [comment]
I can take this one on!

**Comment by marshallj** [comment]
@tpham785 thanks for your interest. @ejaxon and I are in process of refactoring the backend, and the compose.js file you see in this repo will be changing substantially. Would love for you to contribute, but please hold off a bit while we prepare the project for further contributions. Thanks.

**Comment by ejaxon** [comment]
I am closing this. This function has been rewritten now to work with a database backend rather than files.
