### ISSUE TITLE
Design templates & guidelines for common and local content

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#70]
The original [Buncombe County Reentry Resources Hub](http://www.buncombereentryhub.org/) is implemented as a Wordpress website, and individual topic pages were written by a variety of people, so that they don't follow a single standard template.

In the new implementation, content for a topic page for a given county has a strict form:

1. __Common Description__: a block of HTML text with information relevant statewide (or nationally)
2. __Local Description__: a block of HTML text with information relevant to the specific county
3. __National & State Resources__: a list of resources common to all counties
4. __Local Resources__: a list of resources relevant to the specific county
5. __211 Resources__: a list of resources pulled from the 211 database based on categories

where all resources consist of:

- Name
- Short description
- URL
- Category

For counties that do not have tailored content, the topic page will be created only from 1, 3, and 5.

We will need to replicate all the information from the current site, dividing it into common and Buncombe-specific parts. However, before completing that, we need to set up some guidelines for just how the descriptions should be structured and formatted and how resource descriptions should be structured (you can find some resource examples in, e.g., `jurisdictions/buncombe/health/resources_local.json` in the [content repository](https://github.com/CodeForNC/nc-reentry-resources-content). 

The guidelines should be prepared in [this Google doc](https://docs.google.com/document/d/1ohCB0a4YKEJqT9ZyVz26w9EjdCy7irkgoHWz0dl9w7o/edit?usp=sharing).

**Comment by dresean** [comment]
Hi guys, I found a site with local resources for each county here: http://randp.doc.state.nc.us/scripts/htmSQL.exe/docs/hsql/CM/CountyResourceGuide-COquery.hsql 

Just use the county selectors and submit to get numbers to local resources. I think we should categorize the most common resources available to each county and have that listed in a button for "State/Fed Resources" (ex. Goodwill, Salvation Army, etc.)

**Comment by ejaxon** [comment]
Yes, I believe we are linking somewhere to the DPS site and agree that we could use these in the generated resources for specific counties. One issue with the site, however, is that it tends to have out-of-date links

**Comment by dresean** [comment]
Ok, I understand.

**Comment by dresean** [comment]
The final updates to the document are ready. Please let me know if you need anything else done!

**Comment by ejaxon** [comment]
Thanks all! We'll review in the next week and figure out next steps.

**Comment by ejaxon** [comment]
Closing this.
