### ISSUE TITLE
Add a favicon to the site

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#72]
The site does not yet have a favicon (and therefore generates a 404 error message in the JS console every load). Let's at least get a simple default favicon.

**Comment by Sadaajit** [comment]
Have created a favicon and was wondering if you want me to put placeholder code in the file, as I don't know where the image is going to end up in the full project and it will need to be coded for that location.

**Comment by ejaxon** [comment]
@Sadaajit & @marshallj: how about just creating a /public folder on the top level and putting it there. We can also use it for images.

**Comment by marshallj** [comment]
@Sadaajit, I agree with @ejaxon. Just create a folder inside 'reentry-resources-hub' called 'public' and place your favicon inside there. Let me know if you need help submitting a pull request.

**Comment by Sadaajit** [comment]
Have put the favicon in the public folder and tried every permutation of favicon html I found the web, but none of them worked. I think I probably don't have my href correct. I'm not sure how much of  the actual "breadcrumb" of the files I need to include. I thought it would just be /public/favicon.ico. Do I need to include more than that? My terminal is saying 404 - /favicon.ico if that helps. Also, I'm using yarn, which is new to me. After an error does it continue to work with the site? I know Gulp drops you and you have to reconnect. This is so easy with a live site...

**Comment by ejaxon** [comment]
@Sadaajit - I think this probably needs some additional configuration in webpack.config.js. @marshallj - who is best to help with this. I'm not a great expert, but can try to figure out, but if someone already knows, that would be best. Also, I don't see a build target in scripts in package.json - we'll need to add that.

**Comment by Sadaajit** [comment]
@marshallj, @ejaxon has suggested some extra changes in the webpack.config.js and package.json, which I don't know how to do. Is this needed? If so, you'll need to find someone else to do that work, or what would be better is if you have someone that can do the work, that would allow me to work with them. I need to do some collaboration in order to increase my skills.

**Comment by marshallj** [comment]
@Sadaajit looks like Brendan added a favicon when he refactored the project for us. feel free to take a look, its in the public folder. Closing this issue.
