### ISSUE TITLE
User testing for current public site.

### ISSUE THREAD

**Issue by marshallj** [CodeForNC/reentry-resources-hub#75]
We need testers to collaboratively document bugs and issues with the current version of the public NC Reentry Resource Hub website [here](https://docs.google.com/document/d/16-vuF_vA_fn7HUApy_KSI8AP1LNYr0tieGh0O7rZQ64/edit). 

We need testing and documentation on: Chrome, Safari, Firefox, Internet Explorer, Opera, as well as, testing on as many mobile devices as possible, including phones and tablets. 

During testing use the main home page at the '/' route, and Buncombe County's pages at /buncombe/...

**Comment by ejaxon** [comment]
I am closing this since it's duplicated by [this one](https://github.com/CodeForNC/nc-reentry-resources-content/issues/5), where the work actually occurred.
