### ISSUE TITLE
Implement Sass to replace CSS 

### ISSUE THREAD

**Issue by marshallj** [CodeForNC/reentry-resources-hub#77]
Currently the site is styled with CSS. Implement Sass for styling the site using the existing CSS as a guide. Include a transpiler to convert to CSS.

**Comment by marshallj** [comment]
Hi @jandrewwhit. I am making the rounds to check in on the in progress issues. Are you still working on this one. I understand if your time is pulled elsewhere. Just let me know by Friday, so I can put it back in the to do column if needed. Thanks.

**Comment by ejaxon** [comment]
Since we've merged @BlakeGuilloud's pull request on this, can we close, @marshallj?

**Comment by marshallj** [comment]
Closing.
