### ISSUE TITLE
Separate config details from package.json (eslint babel)

### ISSUE THREAD

**Issue by BlakeGuilloud** [CodeForNC/reentry-resources-hub#79]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description
To optimize organization and follow best practice, we should break out the babel config and eslint config from the package.json and create respective files to handle this. This offers tons of benefits, namely: not having to specify which babel-presets you want to load in different build files.

In webpack.config.js:
```javascript
loaders: [
      {
        test: /.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: {
          presets: ['react', 'es2015', 'stage-0'],
        },
      },
    ],
```

after breaking our babel config into it's own rc file, we will be able to eliminate the query key, and the above code turns into:

```javascript
loaders: [
      {
        test: /.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
      },
    ],
```

This will also update our `npm run server` script from:
```javascript
"server": "NODE_ENV=production node_modules/.bin/babel-node --presets react,es2015,stage-0 src/server.js",
```
to:
```javascript
"server": "NODE_ENV=production node_modules/.bin/babel-node src/server.js",
```

While both implementations currently work as intended, it is nice to separate concerns and reuse the same config for multiple build tasks.

**Comment by marshallj** [comment]
Reviewed @BlakeGuilloud PR. All looks great.
