### ISSUE TITLE
Information Design - Architecture Discussion

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#9]
How will we organize information on the site and especially on a topic page. This will help drive the server content architecture discussion.

I'm starting with the assumption that the site will be organized similarly to http://www.buncombereentryhub.org, with a home page, a contact page, and a set of 8 topics.

Each page will consist of a combination of content that is common between counties (general introduction plus federal and state information) plus content that is specifically local plus regional content (i.e., pulled from other counties).

As to types of content, I think we have 3:

- Text block - used for general introductions/descriptions to the topic, or pertaining to federal law, state law or local conditions.
- Highlighted resource - Title, link and description that is more extensive than a simple resource link
- Resource link - title, link and possibly very short description.

Some links will be parametrized - I think we can handle that pretty easily with a simple variable replace convention in content.

Here's a first pass at content organization for a page:

- Common introduction (text block - common to all sites)
- Local introduction (text block - optional additional introduction for local site)
- Highlighted resources (highlighted resources - local)
- List of resources
  - Local (resource links)
  - Regional (resource links)
  - National (resource links)

Note that in the case of a county site that has just been created, there will be no specially created local links, but we'll have some standardized ones via parametrized links to NC211 or DPS information. Should those be listed at the bottom of the local ones? Or do they perhaps follow all the other resources?

**Comment by marshallj** [comment]
This sounds reasonable and well thought out. For the standardized resources, could you clarify? Could we reasonably, (or perhaps even ethically) create all 100 county sites out of the gate and provide all known resources that apply to each county and include a disclaimer for areas where local/regional resources have not been identified yet?

**Comment by ejaxon** [comment]
Probably "parametrized" is a better term than "standardized". Mainly what I mean are the NC211 links where we only need to substitute the correct county name to generate localized results. Not quite sure of the mechanism, but it should be set up so that those links show up in the local section even if the county site is nothing more than a directory with a configuration file setting the county name.

I think it makes total sense to go ahead and create all 100 county sites. There is significant value even just in making the general state- and federal-level information available and the use of parametrized links to 211 resources adds to that. I think too that presenting the task of doing a local site as simply augmenting with pertinent local knowledge makes it feel much less daunting.

**Comment by marshallj** [comment]
For the mechanism for the 211 links, can't we just concatenate it into the jsx (pulled from the data location - file/database) to form the county urls?

**Comment by ejaxon** [comment]
The main question I have re: mechanism is where they're stored. We can create a local site by copying in standard parameterized links, but then we'd have to change all 100 if we wanted to improve them. In any case, hoping to get to that as part of the [server content architecture](https://github.com/CodeForNC/reentry-resources-hub/issues/10) issue this weekend.

**Comment by ejaxon** [comment]
Minor change on the design above to keep things manageable:

- Common introduction (text block - common to all sites)
- Local introduction (text block - optional additional introduction for local site)
- Highlighted resources (highlighted resources - local)
- List of resources
    - Local (resource links)
    - Regional (resource links)
    - Common - national and state (resource links)

All I've changed here is the last one - I don't think it's worth trying to design for a multi-state site.

**Comment by ejaxon** [comment]
@marshallj I have documented this in the [content page](https://github.com/CodeForNC/reentry-resources-hub/blob/content-arch/documentation/content.md) of the documentation. Let me know if you think this is good enough to start with and I'll close this issue.
